export const t = {
  color: {
    textPrimary:   'var(--color-text-primary)',
    textSecondary: 'var(--color-text-secondary)',
    textMuted:     'var(--color-text-muted)',
    textInverse:   'var(--color-text-inverse)',
    bgPage:        'var(--color-bg-page)',
    bgCard:        'var(--color-bg-card)',
    bgSubtle:      'var(--color-bg-subtle)',
    bgBody:        'var(--color-bg-body)',
    border:        'var(--color-border)',
    borderFocus:   'var(--color-border-focus)',
    primary:       'var(--color-primary)',
    primaryHover:  'var(--color-primary-hover)',
    primaryLight:  'var(--color-primary-light)',
    danger:        'var(--color-danger)',
    success:       'var(--color-success)',
    warning:       'var(--color-warning)',
    textStrong:     'var(--color-text-strong)',
    bgDark:         'var(--color-bg-dark)',
    dangerLight:    'var(--color-danger-light)',
    dangerBorder:   'var(--color-danger-border)',
    dangerText:     'var(--color-danger-text)',
    dangerDark:     'var(--color-danger-dark)',
    successLight:   'var(--color-success-light)',
    successBorder:  'var(--color-success-border)',
    successText:    'var(--color-success-text)',
    successAlt:     'var(--color-success-alt)',
    warningBorder:  'var(--color-warning-border)',
    warningText:    'var(--color-warning-text)',
    info:           'var(--color-info)',
    primaryVivid:   'var(--color-primary-vivid)',
    primaryMuted:   'var(--color-primary-muted)',
  },
  font: {
    size: {
      xs:  'var(--font-size-xs)',
      sm:  'var(--font-size-sm)',
      md:  'var(--font-size-md)',
      lg:  'var(--font-size-lg)',
      xl:  'var(--font-size-xl)',
      '2xl': 'var(--font-size-2xl)',
    },
    weight: {
      normal:   'var(--font-weight-normal)',
      medium:   'var(--font-weight-medium)',
      semibold: 'var(--font-weight-semibold)',
      bold:     'var(--font-weight-bold)',
    },
  },
  space: {
    1: 'var(--space-1)',
    2: 'var(--space-2)',
    3: 'var(--space-3)',
    4: 'var(--space-4)',
    5: 'var(--space-5)',
    6: 'var(--space-6)',
    8: 'var(--space-8)',
  },
  radius: {
    sm:   'var(--radius-sm)',
    md:   'var(--radius-md)',
    lg:   'var(--radius-lg)',
    xl:   'var(--radius-xl)',
    pill: 'var(--radius-pill)',
  },
  shadow: {
    sm:       'var(--shadow-sm)',
    card:     'var(--shadow-card)',
    cardHover:'var(--shadow-card-hover)',
    lg:       'var(--shadow-lg)',
  },
} as const

export type Tokens = typeof t
